from_email = "pokealert@example.com"
to_email = "8008675309@txt.att.net"
gmail_smtp_username = "example@gmail.com"
gmail_smtp_password = "passwordhere"

coordinates = ('11.11111111111', '-22.222222222222')

alert_pokemon = set([
  "Charizard",
  "Blastoise",
  "Venusaur",
  "Pikachu",
  "Raichu",
  "Ninetales",
  "Kadabra",
  "Alakazam",
  "Lapras",
  "Snorlax",
  "Dragonair",
  "Dragonite",
  "Omastar",
  "Kabutops",
  "Arcanine",
  "Gengar"
])

exclude_pokemon = set([
  "Diglett",
  "Zubat",
  "Golbat",
  "Doduo",
  "Dodrio",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "NidoranF",
  "Nidorina",
  "NidoranM",
  "Nidorino",
  "Clefairy",
  "Clefable",
  "Jigglypuff",
  "Wigglytuff",
  "Paras",
  "Parasect",
  "Psyduck",
  "Mankey",
  "Poliwag",
  "Machop",
  "Bellsprout",
  "Tentacool",
  "Geodude",
  "Gastly",
  "Krabby",
  "Kingler",
  "Cubone",
  "Koffing",
  "Weezing",
  "Horsea",
  "Seadra",
  "Staryu",
  "Pinsir",
  "Tauros",
  "Venonat",
  "Venomoth",
  "Goldeen",
  "Seaking",
  "Oddish",
  "Gloom",
  "Tangela"
])

